# Site settings
title: "Scott de Jonge"
page_title: "Scott de Jonge - UI/UX designer & Web Developer Brisbane"
email: dejonge.scott@gmail.com
description: "Scott de Jonge is a UI/UX designer & Web developer that designs and builds websites for humans at bigfish.tv."

# Server
baseurl: ""
destination: _site
host: 0.0.0.0
port: 4001
url: http://scottdejonge.com
encoding: UTF-8
timezone: UTC
permalink: /writing/:title

# Collections
collections:
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"

# Excludes
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - commit-hook.sh
  - package.json

# Build settings
markdown: kramdown

# Kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Repo
repo: https://github.com/scottdejonge/scottdejonge.github.io

# Social
twitter: https://twitter.com/scottdejonge
github: https://github.com/scottdejonge
instagram: https://instagram.com/scottdejonge


# Navigation
navigation:
  - text: Home
    url: "/"
  - text: About
    url: "/about/"
  - text: Projects
    url: "/projects/"
  - text: Writing
    url: "/writing/"
